- name: Install and run nginx # this is not mandatory but this is best practice
  hosts: mongodb
  become: yes # this will root access
  tasks:
  - name: Install nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: start nginx
    ansible.bultin.service:
      name: nginx
      state: started   