- name: variable from files
  hosts: localhost
  vars_files:
    - variable.yaml
  tasks:
    - name: printing var
      ansible.builtin.debug:
        msg: I'm learning {{Name}}, Duration is {{DURATIONS}}, Trainer is {{TRAINER}}
