- name: create user
  hosts: localhost
  tasks:
  - name: check user exits or not
    # when you want to run the linux command directly i.e n the case ansible module not available
    # when the user does not exists, ansible treating this failure and come-out by default
    # ignore_errors: true
  ansible.builtin.command: id roboshop
  register: output  #output is variable name
  ignore_errors: true

- name: print the command output
  ansible.builtin.debug:
    msg: "output is: {{output}}"
- name: print exist status
  ansible.builtin.debug:
    msg: "{{output.rc}}"
- name: create user roboshop
  become: yes #we need sudo access for this task only
  ansible.builtin.user:
    name: roboshop
  when: output.rc != 0 #if this expression is true then only this module will run.