- name: loops in ansible
  hosts: localhost # you no need to give username and password through ansible commnd line
  tasks:
  - name: print the name
    ansible.builtin.debug:
      msg: "Hello {{item}}"
    loop:
    - Kesab
    - Raheem
    - john