- name: install Package
  hosts: localhost
  tasks:
  - name: install Package
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
    - ngnix
    - postfix
    - cyrus-sasl-plain
    - mailx