- name: install Package
  hosts: mongodb
  become: yes
  tasks:
  - name: install Package
    ansible.builtin.yum:
      name: "{{item}}"
      state: absent
    loop:
    - nginx
    - postfix
    - cyrus-sasl-plain
    - mailx