- name: install Package
  hosts: mongodb
  become: yes
  tasks:
  - name: install Package
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'nginx', state: 'present'}
    - {name: 'postfix', state: 'absent'}
    - {name: 'cyrus-sasl-plain', state: 'present'}
    - {name: 'mailx', state: 'absent'}